### ISSUE TITLE
r0ck3tz - Incorrect voting count

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-olympus-on-chain-governance-judging#51]
r0ck3tz

medium

# Incorrect voting count

## Summary

The [`castVoteInternal`](https://github.com/sherlock-audit/2024-01-olympus-on-chain-governance/blob/main/bophades/src/external/governance/GovernorBravoDelegate.sol#L433-L462) internal function incorrectly uses the current `block.number` for votes instead of retrieving votes from the previous block.

## Vulnerability Detail

The [`castVoteInternal`](https://github.com/sherlock-audit/2024-01-olympus-on-chain-governance/blob/main/bophades/src/external/governance/GovernorBravoDelegate.sol#L433-L462) internal function of the `GovernorBravoDelegate` contract is utilized by `castVote`, `castVoteWithReason`, and `castVoteBySig` to cast a vote for a given proposal. To accommodate the rebasing nature of `gOHM` tokens, the logic considers the user's votes at the time of proposal creation and at voting time, selecting the minimum. The issue arises from the use of the current `block.number` instead of `block.number - 1` for current votes. This opens the door to multiple scenarios of transferring votes between accounts to artificially inflate the number of votes.

## Impact

The attacker can artificially inflate the voting up to the value of votes at the time of the proposal start by transferring `gOHM` tokens between accounts.

## Code Snippet

- https://github.com/sherlock-audit/2024-01-olympus-on-chain-governance/blob/main/bophades/src/external/governance/GovernorBravoDelegate.sol#L444-L447

## Tool used

Manual Review

## Recommendation

It is recommended to use `block.number - 1` for the `currentVotes`:
```solidity
uint256 currentVotes = gohm.getPriorVotes(voter, block.number - 1);
```

**Comment by r0ck3tzx** [comment]
escalate

The attack vector that I meant is the following:

1. User has multiple accounts with `gOHM` balance at `proposal.startBlock`: `Acc1`, `Acc2`, `Acc3`, `Acc4`
2. User sells most of `gOHM` and only `Acc1` holds tokens
3. At the time of voting `uint256 currentVotes = gohm.getPriorVotes(voter, block.number);` is used so the user just uses `Acc1` and keeps sending `gOHM` between accounts `Acc2`, `Acc3` and `Acc4` to make votes.

I believe the fix is exactly the same as for https://github.com/sherlock-audit/2024-01-olympus-on-chain-governance-judging/issues/37 so probably it would be a dup.

**Comment by sherlock-admin2** [comment]
> escalate
> The attack vector that I meant is the following:
> 
> 1. User has multiple accounts with `gOHM` balance at `proposal.startBlock`: `Acc1`, `Acc2`, `Acc3`, `Acc4`
> 2. User sells most of `gOHM` and only `Acc1` holds tokens
> 3. At the time of voting `uint256 currentVotes = gohm.getPriorVotes(voter, block.number);` is used so the user just uses `Acc1` and keeps sending `gOHM` between accounts `Acc2`, `Acc3` and `Acc4` to make votes.
> 
> I believe the fix is exactly the same as for https://github.com/sherlock-audit/2024-01-olympus-on-chain-governance-judging/issues/37 so probably it would be a dup.

You've deleted an escalation for this issue.

**Comment by nevillehuang** [comment]
@r0ck3tzx You cannot artificially inflate votes when you cannot vote in the first place. 

I think your issue is similar to an ongoing debate whether or not such issues should be valid as seen by my comments [here](https://github.com/sherlock-audit/2023-12-jojo-exchange-update-judging/issues/30#issuecomment-1913114684). If protocol deploys the contracts as is, this attack cannot occur.

**Comment by 0xLienid** [comment]
I think this is invalid just because it gets the functionality of `getPriorVotes` wrong. It's not that it gets the vote count wrong, but it doesn't even execute, it just reverts since `getPriorVotes` requires a previous block.

**Comment by r0ck3tzx** [comment]
@nevillehuang thats a fair point, I guess I should have created proof of concept for this and that would let me discover the correct issue https://github.com/sherlock-audit/2024-01-olympus-on-chain-governance-judging/issues/37

I'm closing this escalation
