### ISSUE TITLE
s1ce - Malicious frontrunner can censor any proposal from being executed due to tx hash collisions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-olympus-on-chain-governance-judging#89]
s1ce

high

# Malicious frontrunner can censor any proposal from being executed due to tx hash collisions

## Summary

A malicious frontrunner can prevent any proposal from being executed through a somewhat complicated attack, that is a result of collisions in the tx hash due to how it is calculated. 

## Vulnerability Detail

First, let's say that there's a proposal that the frontrunner doesn't want to be executed. The frontrunner first makes the exact same proposal (i.e. signature, data, etc). 

The frontrunner requires that both their proposal and the other proposal they don't want to be executed pass. With this assumption, the frontrunner can do the following:

1. Wait for the other party to queue up their proposal
2. Frontrun this with the following actions:
3. Malicious attacker queues up their own proposal which has passed. This will add the txHash, which is calculated as follows, `keccak256(abi.encode(target, value, signature, data, eta))` to `queuedTransactions` and will also add the right `eta` to the proposal. 
4. Malicious attacker cancels their own proposal so it is removed from queuedTransactions, but the eta on the proposal is still there. 
5. Now the malicious attacker allows the other party's proposal to be queued up, and note that it has the same eta. 
6. Malicious attacker calls cancel again (because the code allows re-cancelling an already cancelled txHash), but this time it cancels the other party's proposal due to the tx hash collision. 

The other party now cannot ever requeue their proposal since it is forever in the Queue (and eventually Expired) state, so the proposal has effectively been cancelled. 

Another case where this tx hash collision could cause problems is if the same transaction (target, value, signature, data all same) was queued up in the past, but then cancelled. Later on, the timelock delay was changed so the `eta` of the two end up coinciding. In this case, the proposer of the original cancelled transaction can call cancel again and cancel the new proposal after it is queued up (and it will be put in a state where it can never be queued up again).  

## Impact

Malicious frontrunner can censor any proposal, with some assumptions

## Code Snippet

https://github.com/sherlock-audit/2024-01-olympus-on-chain-governance/blob/main/bophades/src/external/governance/GovernorBravoDelegate.sol#L284

## Tool used

Manual Review

## Recommendation
Add proposal ID to the tx hash calculation

**Comment by IllIllI000** [comment]
The [PR](https://github.com/OlympusDAO/bophades/pull/302) correctly follows the suggested recommendation of adding the `proposalId` to the transaction hashes. The delegate contract correctly includes the `proposalId` in the hash it passes to the two `queuedTransactions()` calls, and properly passes it to the other functions (`queueTransaction()`, `executeTransaction()`, and `cancelTransaction()`). The ID is also added to the emitted timelock events as an `indexed` parameter, staying within the maximum number in all cases.

**Comment by s1ce** [comment]
Escalate

Disagree with the judgement. 

Consider the following case:

1. Tx was queued up in the past
2. Tx was cancelled
3. ETA is changed by the admin to ANYTHING lower than what it currently is
4. There's a risk of the collision and the first proposer can cancel the new queued proposal, without the ability to requeue

This essentially prevents the admin from changing the eta to anything below the current value

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Disagree with the judgement. 
> 
> Consider the following case:
> 
> 1. Tx was queued up in the past
> 2. Tx was cancelled
> 3. ETA is changed by the admin to ANYTHING lower than what it currently is
> 4. There's a risk of the collision and the first proposer can cancel the new queued proposal, without the ability to requeue
> 
> This essentially prevents the admin from changing the eta to anything below the current value

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Czar102** [comment]
I'm not sure I'm getting the argument in the escalation. `eta` can be considered the same as `proposalId` – you can always have a collision of `proposalId` as well. But you won't have exact same proposals coming in at a rate of 1 per second (I assume there are mechanics preventing proposal spam).

Hence, I think this was correctly recognized as a info/low severity issue.

@s1ce any comment?

**Comment by s1ce** [comment]
@Czar102 Let me clarify in a few hours. It is more complex than that.

**Comment by s1ce** [comment]
@Czar102 

First off, there can never be a collision in `proposalId` as you mentioned (the system actively prevents this), but there can be in `eta`. The crux of this issue is that the attacker will create this collision on purpose, and can control it to some extent. 

There are a few impacts here, I would like to explain them more in depth:

1. For the first impact, sponsor said:

"Not a medium. Relies on the malicious proposer being able to singlehandedly pass a proposal and get through the whole proposal process without being canceled or vetoed prior to queueing."

This is not entirely true; the proposal they would be proposing is not entirely malicious (it would just be an exact copy of someone else's proposal), so there is not really a reason for people to vote against it / veto it inherently. After their proposal is queued up, they can frontrun the other person's attempt to queue (they will get the same eta since it is the same `block.timestamp`), cancel their own proposal, and **permanently** prevent them from passing the proposal. Of course, this relies on both the attacker and other person's proposal to pass and be eligible for queuing initially, but in my opinion this is pretty reasonable if it just a parameter update (for example, both proposals decide to update the same parameter in the same contract to the same value). 

4. The second impact is structured a bit differently and requires an assumption. 

Let's say that an entity queues up a proposal at timestamp 100. The current eta is `50`. The eta for this transaction will be `150`. Later, it is cancelled by the entity. 

Admin ends up changing the `eta` to `25` later on, due to some proposal. Another user queues up the same transaction at timestamp `125`, so the ETAs now collide (they both have the same eta of `150`). The first entity can now re-cancel their already cancelled proposal and permanently cancel the user's new proposal. It is permanently prevented from passing. 

I agree that the chance of either of these happening is probably between 1 - 2% ever, but I do think the impact if they do happen is sufficiently large to the point where this should be labeled a medium. Let me know if you have any questions or need additional information.

**Comment by Czar102** [comment]
I agree that it's a bit more complex than I initially thought. I appreciate the full explanation. I also inspected some relevant parts of the code.

From my observations, the transaction in the timelock has nonzero `eta`. Proposal's `eta` becomes nonzero only after the proposal gets passed (during queueing), meaning that the attacker would also need to get their proposal passed. And then a collision would need to happen *after queueing*. That's impossible, since there is an [explicit check preventing that](https://github.com/sherlock-audit/2024-01-olympus-on-chain-governance/blob/main/bophades/src/external/governance/GovernorBravoDelegate.sol#L245-L246).

Regarding the second impact, it seems it may happen, but is highly unusual for any real life set of time settings to happen. Additionally, you would need to schedule at an exact second to do that. On top of that, the most the attacker can do is delay the execution in this extreme scenario by a single governance cycle (given that they executed the exact same transaction as the previous proposal, and in the meantime the timelock length has been decreased, so that the attacker got the exact timestamp of the queueing transaction right to collide `eta`). Hence, I think this issue is a valid low.

**Comment by s1ce** [comment]
@Czar102 Ah it is possible on the first impact (again it is complicated), let me explain a bit better.

Let me illustrate this from the perspective of the attacker. 

1. As the malicious attacker, first propose the exact same proposal as the other proposal you want to get cancelled. 
2. Your proposal and the other proposal pass
3. You see the other user attempt to queue up their proposal
4. Frontrun this by queueing up your proposal
5. Immediately cancel your proposal (so your proposal is no longer queued); this helps bypass the check you mentioned
6. Now let them queue up their proposal (so it goes through and bypasses the check, since you canceled)
7. Cancel your proposal again (there is no check preventing you from cancelling twice), thus cancelling their proposal too.

I can also code up a quick PoC if you want proof that this is legitimate. 

Regarding that the attacker must also get their proposal passed, yes, I agree that this is a requirement. However, it's not like their proposal is anything malicious (it just copies the other proposal, which may just be a parameter update for example), so I think it is very possible.

**Comment by Czar102** [comment]
I think I understood the impact sufficiently already.

> Regarding that the attacker must also get their proposal passed, yes, I agree that this is a requirement. However, it's not like their proposal is anything malicious (it just copies the other proposal, which may just be a parameter update for example), so I think it is very possible.

That's true, nevertheless the governance would need to allow two proposals to set a parameter to the same value in the same time? I think it's clear that it's not intended behavior of parties involved, and on the off-chance it happens, one can always use flashbots.
Even if this gets exploited, it shouldn't be an issue to create a new proposal, this time make sure no two same actions' proposals pass. I think it's not severe enough to be considered a Medium severity issue by Sherlock, and the difficulty of exploiting this is very high (the attacker needs to have their proposal accepted).

Regarding the escalation, I don't understand how point 3 is possible and why would any non-malicious admin do something like that.

Planning to reject the escalation and leave the issue as is.

**Comment by Czar102** [comment]
Result:
Low
Has duplicates

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [s1ce](https://github.com/sherlock-audit/2024-01-olympus-on-chain-governance-judging/issues/89/#issuecomment-1917458819): rejected
